#!/bin/zsh
#####################################################################

use --group media audio/pulseaudio/volume

#####################################################################

media.audio.pulseaudio.volume.parse.usage

#####################################################################

MAIN() { media.audio.pulseaudio.volume $@; }
