#!/bin/zsh
#####################################################################

use audio/pulseaudio/volume --group media

#####################################################################

media.audio.pulseaudio.volume.parse.usage

#####################################################################

MAIN() { media.audio.pulseaudio.volume $@; }
