#!/usr/bin/env zsh
use --group dotwryn office/memo
#####################################################################

MAIN() {
	local MEMO_NAME=$(dotwryn.office.memo.list-all | utils.fzf.user-input 'select/create a memo')
	[ "${MEMO_NAME}" ] || utils.abort

	echo.debug -v MEMO_NAME

	MEMO_FILE="${MEMO__DIR}/${MEMO_NAME}.${MEMO__FILETYPE}"

	[ ! -f ${MEMO_FILE} ] && {
		echo.status "creating memo '$MEMO_NAME'"
		echo "# $MEMO_NAME" > "$MEMO_FILE" \
			&& echo.success "created memo '$MEMO_NAME'" \
			|| utils.fail 1 "failed to create '$MEMO_FILE'" \
			;
	}

	DATESTRING="## $(date '+%A, %B %-d, %Y')"
	grep -q "$DATESTRING" "$MEMO_FILE" || echo "$DATESTRING" >> "$MEMO_FILE"

	utils.io.edit "${MEMO_FILE}"
}
