#!/bin/zsh
use desktop/notify --group dotwryn

DEPENDENCIES+=(i3-nagbar)
#####################################################################

MAIN() {
	i3-nagbar \
			-t warning \
			-m 'Do you really want to exit i3?' \
			-B 'Yes' "notify-send 'system' 'exiting i3...' -i face-tired; i3-msg exit" \
		|| NOTIFY_ERROR 'unable to launch i3-nagbar'
}
