#!/bin/zsh
DEPENDENCIES+=()
REQUIRED_ENV+=()

use desktop/colorscheme --group dotwryn

CHECK_ENVIRONMENT
#####################################################################
SET_THEME alternate
i3-sensible-terminal &
PID=$!
sleep 0.1
SET_THEME main
wait $!
