_COLORSCHEME_FILE__polybar="${DOTWRYN}/config/user/polybar/theme.ini"

_GENERATE_THEME__polybar() {
	echo "# do not edit; generated by scwrypts
# theme : ${THEME_NAME}
[colors]
background     = #$(_GET_HEX .polybar.background .background)
foreground     = #$(_GET_HEX .polybar.foreground .foreground)
background-alt = #$(_GET_HEX .polybar.background-alt .selection.background)
foreground-alt = #$(_GET_HEX .polybar.foreground-alt .selection.foreground)
primary        = #$(_GET_HEX .polybar.primary    .material.base.primary   .ansi.green.regular)
secondary      = #$(_GET_HEX .polybar.secondary  .material.base.secondary .ansi.blue.regular)
alert          = #$(_GET_HEX .polybar.alert      .material.base.error     .ansi.red.regular)
disabled       = #$(_GET_HEX .polybar.disabled   .ansi.gray.regular)

primary-gradient-0   = #$(_GET_HEX .polybar.primary-gradient-0     .material.primary.700   .ansi.green.regular)
primary-gradient-1   = #$(_GET_HEX .polybar.primary-gradient-1     .material.primary.600   .ansi.green.regular)
primary-gradient-2   = #$(_GET_HEX .polybar.primary-gradient-2     .material.primary.500   .ansi.green.regular)
primary-gradient-3   = #$(_GET_HEX .polybar.primary-gradient-3     .material.primary.400   .ansi.green.regular)
primary-gradient-4   = #$(_GET_HEX .polybar.primary-gradient-4     .material.primary.300   .ansi.green.regular)

secondary-gradient-0 = #$(_GET_HEX .polybar.secondary-gradient-0   .material.secondary.700 .ansi.blue.regular )
secondary-gradient-1 = #$(_GET_HEX .polybar.secondary-gradient-1   .material.secondary.600 .ansi.blue.regular )
secondary-gradient-2 = #$(_GET_HEX .polybar.secondary-gradient-2   .material.secondary.500 .ansi.blue.regular )
secondary-gradient-3 = #$(_GET_HEX .polybar.secondary-gradient-3   .material.secondary.400 .ansi.blue.regular )
secondary-gradient-4 = #$(_GET_HEX .polybar.secondary-gradient-4   .material.secondary.300 .ansi.blue.regular )
" | sed '$d' > "${_COLORSCHEME_FILE__polybar}"
}

_SET_THEME__polybar() {
	return 0  # theme is referenced explicitly after generation
}
