#!/bin/zsh
DEPENDENCIES+=()
REQUIRED_ENV+=()

use desktop/colorscheme --group dotwryn

CHECK_ENVIRONMENT
#####################################################################

MAIN() {
	unset USAGE
	SET_THEME $@
}

#####################################################################
MAIN $@
