#!/bin/zsh

# standard AWS environment variables used by awscli and other tools
export AWS_ACCOUNT=088935110352
export AWS_PROFILE=yage
export AWS_REGION=us-east-2

# fully-qualified path to mount the EFS drive
export AWS__EFS__LOCAL_MOUNT_POINT=/mnt/efs/yage

# s3 bucket name and filesystem targets for media backups
export AWS__S3__MEDIA_BUCKET=yage
export AWS__S3__MEDIA_TARGETS=

# custom i3 configuration settings
export I3__BORDER_PIXEL_SIZE=
export I3__DMENU_FONT_SIZE=
export I3__GLOBAL_FONT_SIZE=
export I3__MODEL_CONFIG=$DOTWRYN/config/i3.conf

# linear.app project management configuration
export LINEAR__API_TOKEN=

# redis connection credentials
export REDIS_AUTH=
export REDIS_HOST=
export REDIS_PORT=
