#!/bin/zsh
#####################################################################
### scwrypts runtime configuration ##################################
#####################################################################

# whether or not to deploy to production (0 = dev (default), 1 = prod)
export IN_PRODUCTION=

#####################################################################

# standard AWS environment variables used by awscli and other tools
export AWS_ACCOUNT=
export AWS_PROFILE=
export AWS_REGION=

# fully-qualified path to mount the EFS drive
export AWS__EFS__LOCAL_MOUNT_POINT=

# details for a directus instance
export DIRECTUS__API_TOKEN=
export DIRECTUS__BASE_URL=

# details for discord bot
export DISCORD__BOT_TOKEN=
export DISCORD__DEFAULT_AVATAR_URL=
export DISCORD__DEFAULT_CHANNEL_ID=

# custom i3 configuration settings
export I3__BORDER_PIXEL_SIZE=3
export I3__DMENU_FONT_SIZE=18
export I3__GLOBAL_FONT_SIZE=16
export I3__MODEL_CONFIG=

# linear.app project management configuration
export LINEAR__API_TOKEN=

# s3 bucket name and filesystem targets for media backups
export MEDIA_SYNC__S3_BUCKET=
export MEDIA_SYNC__TARGETS=(_____       .porn_____      Documents_____  Media_____      Pictures_____)_____

# redis connection credentials
export REDIS_AUTH=
export REDIS_HOST=
export REDIS_PORT=

# twilio account / credentials
export TWILIO__ACCOUNT_SID=
export TWILIO__API_KEY=
export TWILIO__API_SECRET=
export TWILIO__DEFAULT_PHONE_FROM=
export TWILIO__DEFAULT_PHONE_TO=

#####################################################################
