#!/bin/bash
echo Setting up preferred utilities...
local INSTALL_LOCATION='~/.wryn/new_computer_setup'

sudo xcode-select --install;
brew update; # install brew

brew --version;
[ $? -ne 0 ] && echo failed to install homebrew && return 1

brew update; # install brew packages

for package in $(cat $INSTALL_LOCATION/osx/brew_packages); do
	brew install "$package"
done;

# mssql install
#brew install freetds@0.91
#brew link --force  freedts@0.91
#brew tap microsoft/mssqul-release https://github.com/Microsoft/homebrew-m2
#brew update
#brew install --no-sandbox msodbcsql

brew services start postgresql

# use ~/.bashrc instead
[[ ! -f ~/.bashrc ]] && touch ~/.bashrc
echo '[[ -s ~/.bashrc ]] && source ~/.bashrc' >> ~/.bash_profile
cat $INSTALL_LOCATION/osx/rcpathvars >> ~/.bashrc

# python packages
pip3 install -r pip_packages
