#!/bin/zsh
source "$HOME/.config/wryn/env.zsh" && LOAD_ZSH_UTILS
#####################################################################

UPDATE() {
	local VIM_PATH="$HOME/.local/share/source-packages/vim"

	VIM_INSTALL --only-pull || return 1

	cd "$VIM_PATH"
	__STATUS 'configuring vim'
	./configure \
			--with-features=huge \
			--enable-cscope \
			--enable-gtk2-check \
			--enable-gtk3-check \
			--with-x \
			--enable-gui=auto \
			--enable-luainterp=yes \
			--enable-perlinterp=yes \
			--enable-python3interp=yes \
			--enable-rubyinterp=yes \
			--enable-terminal \
		&& __SUCCESS 'finished configuring vim' \
		|| __FAIL 3 'failed to configure vim (see above)' \
		;

	VIM_INSTALL $@ --only-build || __FAIL 2 'vim build failed (try with --clean for make clean)'
}

VIM_INSTALL() {
	"$DOTWRYN/zsh/plugins/scwrypts/scwrypts" --env local --no-log \
		zsh/git/package/install -- \
			--target-url 'https://github.com/vim/vim.git' \
			--local-name 'vim' \
			--update \
			$@
}

#####################################################################
UPDATE $@
