#!/bin/sh
# do not edit; generated by scwrypts
# theme : main
#
# source this file to apply colorscheme to linux getty
#
[[ "$TERM" =~ ^linux$ ]] || return 0
/bin/echo -e " ]P0000505 ]P1c80064 ]P211bb98 ]P36911aa ]P42262bb ]P59922dd ]P622ccba ]P7d0f0f0 ]P8ff44ff ]P944dddd ]PAaa44ff ]PB229df6 ]PCdd88ff ]PD88ffff ]PEd0f0f0 ]PF7e707e "
[ ! $NO_CLEAR ] && clear
return 0
 sed $d
