#!/bin/sh
# do not edit; generated by scwrypts
# theme : burning-death
#
# source this file to apply colorscheme to linux getty
#
[[ "$TERM" =~ ^linux$ ]] || return 0
/bin/echo -e " ]P0570406 ]P1dc1a4e ]P23296eb ]P3c24022 ]P45ab5e0 ]P5df5041 ]P634549b ]P7ffeaec ]P8f08ba4 ]P98eadf8 ]PAf19892 ]PBb9e5f4 ]PCf19892 ]PD99bafb ]PEd0f0f0 ]PF7e707e "
[ ! $NO_CLEAR ] && clear
return 0
 sed $d
