#!/bin/sh
# do not edit; generated by scwrypts
# theme : halloween
#
# source this file to apply colorscheme to linux getty
#
[[ "$TERM" =~ ^linux$ ]] || return 0
/bin/echo -e " ]P0000505 ]P100f900 ]P2ff6f00 ]P38b41d5 ]P4ac0041 ]P5750dcc ]P600f900 ]P7d0f0f0 ]P8a3ff90 ]P9ffe082 ]PAbb94e6 ]PBff283e ]PCd6bff0 ]PDcbffbe ]PEd0f0f0 ]PF7e707e "
[ ! $NO_CLEAR ] && clear
return 0
 sed $d
