_COLORSCHEME_FILE__alacritty_toml="$ACTIVE_THEME_PATH/alacritty.toml"
_COLORSCHEME_FILE__alacritty_yaml="$ACTIVE_THEME_PATH/alacritty.yaml"

_GENERATE_THEME__alacritty() {
	echo "# do not edit; generated by scwrypts
# theme : $THEME_NAME
[colors.cursor]
cursor = '0x$CURSOR'

[colors.primary]
background = '0x$BACKGROUND'
foreground = '0x$FOREGROUND'

[colors.normal]
black   = '0x$BLACK'
red     = '0x$RED'
green   = '0x$GREEN'
yellow  = '0x$YELLOW'
blue    = '0x$BLUE'
magenta = '0x$MAGENTA'
cyan    = '0x$CYAN'
white   = '0x$WHITE'

[colors.bright]
black   = '0x$BRIGHT_BLACK'
red     = '0x$BRIGHT_RED'
green   = '0x$BRIGHT_GREEN'
yellow  = '0x$BRIGHT_YELLOW'
blue    = '0x$BRIGHT_BLUE'
magenta = '0x$BRIGHT_MAGENTA'
cyan    = '0x$BRIGHT_CYAN'
white   = '0x$BRIGHT_WHITE'
" | sed '$d' > "$_COLORSCHEME_FILE__alacritty_toml"

	# backwards yaml compatibility
	echo "---   # yamllint disable rule:colons
# do not edit; generated by scwrypts
# theme : $THEME_NAME
colors:
  primary:
    background: '0x$BACKGROUND'
    foreground: '0x$FOREGROUND'
  cursor:
    cursor: '0x$CURSOR'
  normal:
    black:   '0x$BLACK'
    red:     '0x$RED'
    green:   '0x$GREEN'
    yellow:  '0x$YELLOW'
    blue:    '0x$BLUE'
    magenta: '0x$MAGENTA'
    cyan:    '0x$CYAN'
    white:   '0x$WHITE'
  bright:
    black:   '0x$BRIGHT_BLACK'
    red:     '0x$BRIGHT_RED'
    green:   '0x$BRIGHT_GREEN'
    yellow:  '0x$BRIGHT_YELLOW'
    blue:    '0x$BRIGHT_BLUE'
    magenta: '0x$BRIGHT_MAGENTA'
    cyan:    '0x$BRIGHT_CYAN'
    white:   '0x$BRIGHT_WHITE'
" | sed '$d' > "$_COLORSCHEME_FILE__alacritty_yaml"

	local TRANSPARENCY_OVERRIDE=$(cat "$SOURCE_THEME" | YQ -r '.alacritty.transparency' | grep -v '^null$')
	[ $TRANSPARENCY_OVERRIDE ] && {
		printf "[window]\nopacity = $TRANSPARENCY_OVERRIDE\n" >> "$_COLORSCHEME_FILE__alacritty_toml"
		printf "window:\n  opacity: 0.8" >> "$_COLORSCHEME_FILE__alacritty_yaml"
	}

	return 0
}

_SET_THEME__alacritty() {
	ln -sf "$_COLORSCHEME_FILE__alacritty_toml" "$HOME/.config/alacritty/theme.toml"
	ln -sf "$_COLORSCHEME_FILE__alacritty_yaml" "$HOME/.config/alacritty/theme.yml"
}
