_COLORSCHEME_FILE__getty="$ACTIVE_THEME_PATH/getty.sh"

_GENERATE_THEME__getty() {
	echo "#!/bin/sh
# do not edit; generated by scwrypts
# theme : $THEME_NAME
#
# source this file to apply colorscheme to linux getty
#
[[ \"\$TERM\" =~ ^linux$ ]] || return 0
/bin/echo -e \" \
\\e]P0$BACKGROUND \
\\e]P1$RED \
\\e]P2$GREEN \
\\e]P3$YELLOW \
\\e]P4$BLUE \
\\e]P5$MAGENTA \
\\e]P6$CYAN \
\\e]P7$FOREGROUND \
\\e]P8$BRIGHT_RED \
\\e]P9$BRIGHT_GREEN \
\\e]PA$BRIGHT_YELLOW \
\\e]PB$BRIGHT_BLUE \
\\e]PC$BRIGHT_MAGENTA \
\\e]PD$BRIGHT_CYAN \
\\e]PE$WHITE \
\\e]PF$BRIGHT_WHITE \
\"
[ ! \$NO_CLEAR ] && clear
return 0
" sed '$d' > "$_COLORSCHEME_FILE__getty"
}

_SET_THEME__getty() {
	ln -sf "$_COLORSCHEME_FILE__getty" "$HOME/.config/wryn/tty-colorscheme"
}
