_COLORSCHEME_FILE__polybar="$ACTIVE_THEME_PATH/polybar.ini"

_GENERATE_THEME__polybar() {
	echo "# do not edit; generated by scwrypts
# theme : $THEME_NAME
[colors]
background     = #$(_GET_HEX .polybar.background .background)
foreground     = #$(_GET_HEX .polybar.foreground .foreground)
background-alt = #$(_GET_HEX .polybar.background-alt .selection.background)
foreground-alt = #$(_GET_HEX .polybar.foreground-alt .selection.foreground)
primary        = #$(_GET_HEX .polybar.primary    .material.base.primary   .ansi.green.regular)
secondary      = #$(_GET_HEX .polybar.secondary  .material.base.secondary .ansi.blue.regular)
alert          = #$(_GET_HEX .polybar.alert      .material.base.error     .ansi.red.regular)
disabled       = #$(_GET_HEX .polybar.disabled   .ansi.gray.regular)
" | sed '$d' > "$_COLORSCHEME_FILE__polybar"
}

_SET_THEME__polybar() {
	return 0  # theme is referenced explicitly after generation
}
