_COLORSCHEME_FILE__rofi="$ACTIVE_THEME_PATH/rofi.rasi"

_GENERATE_THEME__rofi() {
	echo "/**
 * do not edit; generated by scwrypts
 * theme : $THEME_NAME
 **/

*{
	background:     #$(_GET_HEX .rofi.background      .background);
	foreground:     #$(_GET_HEX .rofi.foreground      .foreground);
	background-alt: #$(_GET_HEX .rofi.background-alt  .material.primary.300             .selection.background);
	selected:       #$(_GET_HEX .rofi.selected        .material.foreground.primary.300  .selection.foreground);
	active:         #$(_GET_HEX .rofi.active          .material.base.primary   .ansi.green.regular);
	urgent:         #$(_GET_HEX .rofi.urgent          .material.base.error     .ansi.red.regular  );
}
" | sed '$d' > "$_COLORSCHEME_FILE__rofi"
}

_SET_THEME__rofi() {
	return 0  # theme is referenced explicitly after generation
}
