---  # local.altaria > scwrypts
media-sync:
  targets:
    value:
      - Pictures
      - Documents
      - Media
      - .local/.porn
      - Games/roms
      - .local/share/dolphin-emu
      - Games/archives
