---  # local > scwrypts
aws:
  account:
    value: "088935110352"
  efs:
    local-mount-point:
      value: /mnt/efs/yage
  profile:
    value: yage
  region:
    value: us-east-2
directus:
  base-url:
    value: https://heretic.directus.app
discord:
  content-header:
    value: '<@380809228450922507> '
media-sync:
  s3-bucket:
    value: yage
twilio:
  account-sid:
    value: ACac926b109b3cd8a78685a2a0994d0271
