---  # local.umbreon > scwrypts
discord:
  default-avatar-url:
    value: https://heretic.directus.app/assets/9c975a20-d6f3-47f5-8f77-74014f5d0024
  default-username:
    value: umbreon
media-sync:
  targets:
    value:
      - Documents
      - Pictures
      - .local/.porn
      - Media/commission
      - Media/music
      - Media/recordings
      - Media/sfx
