#!/bin/zsh
source $HOME/.wryn/env/env.zsh
XSERVER_DIR="$DOTWRYN/config/xserver"

AT_HOME(){
	xrandr -q | grep -q 'HDMI-0 connected';
}

AT_RENT() {
	xrandr -q | grep -q 'DP-[0134] connected';
}

if AT_HOME; then
	"$XSERVER_DIR/screenlayout/homedock_hdmionly.sh";
elif AT_RENT; then
	"$XSERVER_DIR/screenlayout/workdock.sh";
else;
	"$XSERVER_DIR/screenlayout/undock.sh";
fi
