#!/bin/sh
CUSTOM_DMENU_COMMANDS="$HOME/.local/custom_dmenu"
[ ! -d $CUSTOM_DMENU_COMMANDS ] && mkdir $CUSTOM_DMENU_COMMANDS

export PATH="$CUSTOM_DMENU_COMMANDS:$PATH"

"$HOME/.wryn/config/xserver/set_randr_layout" &

exec i3
