#!/bin/zsh
#####################################################################

DEPENDENCIES+=()
REQUIRED_ENV+=()

use ssh --group remote

CHECK_ENVIRONMENT

#####################################################################

REMOTE__LOGIN $@
