---  # yamllint disable rule:colons
# DEPRECATED; please refer to alacritty.toml
import:
  - ~/.config/alacritty/theme.yml
  - ~/.config/alacritty/local.yml

window:
  opacity: 0.8

font:
  glyph_offset:
    x: 0
    y: 1

  normal:
    family: Monaspace Neon

  bold:
    family: Monaspace Argon

  italic:
    family: Monaspace Radon
