---  # used by scwrypts i3 generate config (override at ~/.config/i3/local.yaml)
font:
  size: 14
  family: >-
    pango:Monaspace Argon,
    pango:Noto Color Emoji,
    pango:Symbols Nerd Font,
    FontAwesome

application-launcher: >-
  "rofi -theme $DOTWRYN/config/rofi.theme.rasi -modes drun,run -show run"

# application-launcher: >-
#   dmenu_run -c -l 5 -fn 'DejaVuSansMono Nerd Font-25'

gaps:
  inner: 0
  outer: 0

statusbar:
  # supported values are 'polybar' and 'i3status'
  type: polybar

# a list of i3config excerpts that should be appended to the generated config
i3configs: []
