#!/bin/zsh
#####################################################################
### scwrypts runtime configuration (group 'dotwryn') ################
#####################################################################

# directory containing sound effects
export DESKTOP__SFX_PATH="$HOME/Media/sfx"
export DESKTOP__WALLPAPER_PATH="$HOME/Pictures/bg"

# home server data
export WRYN__SERVER_HOSTNAMES=
