#!/bin/zsh
#####################################################################
#####################################################################
source /root/.wryn/.docker/session/start-background

[ -t 0 ] && tmux a -t $SESSION || echo -e "\\033[1;32m
REMINDER: connect by executing 'tmux a -t $SESSION'
\\033[0m"

until ! tmux list-sessions 2>/dev/null | awk '{print $1;}' | grep -q "${SESSION}:"; do sleep 1; done
#####################################################################
echo -e "\\033[1;31m=====================================================================\\033[0m
\\033[1;32mExiting Debugger; see you next time!\\033[0m
\\033[1;31m=====================================================================\\033[0m"
