#!/bin/bash
set $mod Mod4
font pango:Liberation Mono 8
floating_modifier $mod
bindsym $mod+Return exec i3-sensible-terminal
bindsym $mod+Shift+q kill
bindsym $mod+d exec --no-startup-id j4-dmenu-desktop
bindsym $mod+o exec --no-startup-id j4-dmenu-desktop
bindsym $mod+l exec --no-startup-id i3lock -c 111111
bindsym $mod+c exec --no-startup-id google-chrome-stable
bindsyn $mod+p exec --no-startup-id ~/.screenlayout/auto.sh
bindsym --whole-window $mod+button3 workspace next_on_output
bindsym --whole-window $mod+shift+button3 exec xdotool key --clearmodifiers ctrl+Tab
bindsym --whole-window $mod+shift+ctrl+button3 exec xdotool key --clearmodifiers ctrl+Shift+Tab
bindsym $mod+m move workspace to output right
bindsym $mod+Shift+m move workspace to output left
bindsym $mod+Left focus left
bindsym $mod+Down focus down
bindsym $mod+Up focus up
bindsym $mod+Right focus right
bindsym $mod+Shift+j move left
bindsym $mod+Shift+k move down
bindsym $mod+Shift+l move up
bindsym $mod+Shift+semicolon move right
bindsym $mod+Shift+Left move left
bindsym $mod+Shift+Down move down
bindsym $mod+Shift+Up move up
bindsym $mod+Shift+Right move right
bindsym $mod+h split h
bindsym $mod+v split v
bindsym $mod+f fullscreen toggle
bindsym $mod+s layout stacking
bindsym $mod+w layout tabbed
bindsym $mod+e layout toggle split
bindsym $mod+Shift+space floating toggle
bindsym $mod+space focus mode_toggle
bindsym $mod+a focus parent
bindsym $mod+1 workspace 1
bindsym $mod+2 workspace 2
bindsym $mod+3 workspace 3
bindsym $mod+4 workspace 4
bindsym $mod+5 workspace 5
bindsym $mod+6 workspace 6
bindsym $mod+7 workspace 7
bindsym $mod+8 workspace 8
bindsym $mod+9 workspace 9
bindsym $mod+0 workspace 10
bindsym $mod+Shift+1 move container to workspace 1
bindsym $mod+Shift+2 move container to workspace 2
bindsym $mod+Shift+3 move container to workspace 3
bindsym $mod+Shift+4 move container to workspace 4
bindsym $mod+Shift+5 move container to workspace 5
bindsym $mod+Shift+6 move container to workspace 6
bindsym $mod+Shift+7 move container to workspace 7
bindsym $mod+Shift+8 move container to workspace 8
bindsym $mod+Shift+9 move container to workspace 9
bindsym $mod+Shift+0 move container to workspace 10
bindsym $mod+Shift+c reload
bindsym $mod+Shift+r restart
bindsym $mod+Shift+e exec "i3-nagbar -t warning -m 'You pressed the exit shortcut. Do you really want to exit i3? This will end your X session.' -b 'Yes, exit i3' 'i3-msg exit'"
mode "resize" {
        bindsym j resize shrink width 10 px or 10 ppt
        bindsym k resize grow height 10 px or 10 ppt
        bindsym l resize shrink height 10 px or 10 ppt
        bindsym semicolon resize grow width 10 px or 10 ppt
        bindsym Left resize shrink width 10 px or 10 ppt
        bindsym Down resize grow height 10 px or 10 ppt
        bindsym Up resize shrink height 10 px or 10 ppt
        bindsym Right resize grow width 10 px or 10 ppt
        bindsym Return mode "default"
        bindsym Escape mode "default"
}
bindsym $mod+r mode "resize"
bar {
        status_command i3blocks -c ~/i3blocks.conf
        position top
        tray_output DisplayPort-1
 
        colors {
        }
}
workspace 1 output DisplayPort-1
workspace 2 output DisplayPort-0
workspace 5 output DisplayPort-0
workspace 3 output eDP
bindsym XF86AudioPlay exec playerctl play-pause
bindsym XF86AudioNext exec playerctl next
bindsym XF86AudioPrev exec playerctl previous
bindsym $mod+comma exec code ~/.config/i3/config
for_window [class="^.*"] border pixel 1
#exec --no-startup-id compton &
assign [class="Chromium-browser"] 3
assign [class="Code"] 2
assign [class="Google-chrome"] 5
exec --no-startup-id chromium-browser
exec --no-startup-id google-chrome
exec --no-startup-id code
exec --no-startup-id .screenlayout/auto.sh
exec --no-startup-id iwconfig wlp3s0 txpower 10dBm
