#!/bin/sh
ENGINE="$(which canberra-gtk-play) -f"
SFX="$HOME/Personal/sfx";


PLAY() {
	eval "$ENGINE" "$SFX/$1"
}

case $1 in
	volume    ) PLAY yaru-message.oga ;;
	mute      ) PLAY smooth-dialog-warning.oga ;;
	backlight ) PLAY yaru-audio-volume-change.oga ;;
	login     ) PLAY yaru-desktop-login.oga ;;
	logout    ) PLAY smooth-desktop-login.oga ;;

	* ) ls $SFX ;;
esac

alsa-front-center.wav
alsa-front-left.wav
alsa-front-right.wav
alsa-noise.wav
alsa-rear-center.wav
alsa-rear-left.wav
alsa-rear-right.wav
alsa-side-left.wav
alsa-side-right.wav
freedesktop-bell.oga
freedesktop-camera-shutter.oga
freedesktop-complete.oga
freedesktop-message.oga
smooth-count-down.oga
smooth-desktop-login-1.oga
smooth-desktop-login-2.oga
smooth-desktop-login.oga
smooth-desktop-logout.oga
smooth-dialog-error.oga
smooth-dialog-information.oga
smooth-dialog-question.oga
smooth-dialog-warning.oga
smooth-message-new-instant.oga
smooth-message-sent-instant.oga
smooth-phone-incoming-call.oga
smooth-phone-outgoing-busy.oga
smooth-phone-outgoing-calling.oga
smooth-trash-empty.oga
yaru-audio-volume-change.oga
yaru-battery-low.oga
yaru-bell.oga
yaru-complete.oga
yaru-desktop-login.oga
yaru-device-added.oga
yaru-device-removed.oga
yaru-dialog-error.oga
yaru-message-new-instant.oga
yaru-message.oga
