#!/bin/zsh

alias gdrive="RCLONE_GOOGLE_DRIVE_MOUNT"

RCLONE_GOOGLE_DRIVE_MOUNT() {
	local RCLONE_REMOTE_NAME='google-drive';

	clear;
	figlet GOOGLE DRIVE CONNECTION | lolcat;
	echo -e "\e[3m(C-c to close)\e[0m";

	rclone mount "$RCLONE_REMOTE_NAME:$1" "$HOME/GoogleDrive"
}
