#!/bin/zsh
source "$HOME/.wryn/env/env.zsh"

RC_DIR="$DOTWRYN/zsh"

# source .wryn/zsh files
for file in $(find $RC_DIR -maxdepth 1 -type f ! -name 'rc'); do source $file; done;

# osx
if [[ "$OSTYPE" == "darwin"* ]]; then
	for file in $(find $RC_DIR/osx -type f); do source $file; done;
fi

# linux
if [[ "$OSTYPE" == "linux-gnu" ]]; then
	for file in $(find $RC_DIR/linux -type f); do source $file; done;
fi

# --- ViM as default editor -----------------------------------
export EDITOR='vim'
export VISUAL='vim'

# --- Welcome message -----------------------------------------
exec figlet "Welcome, beautiful" | lolcat; echo; cowsay -p "damn u sexy" | lolcat; 

alias restart='clear; source ~/.zshrc; echo'

# --- !@#$ Aliases --------------------------------------------
alias clera='clear';
alias sl='sl -alF | lolcat';

# --- ZSH Completion Styles -----------------------------------
zmodload -i zsh/complist;

zstyle ':completion:*' menu select;
bindkey -M menuselect '^M' .accept-line; # don't require 'return' to select menu item
