#!/bin/zsh

CLISP="clisp lisp"
 TEXT="txt md js";
  WEB="css scss less html php cshtml json"
   JS="ts tsx js"
    C="cpp h c cs"

FILES_TO_EDIT="$CLISP $TEXT $WEB $JS $C";

for filetype in ${(s/ /)FILES_TO_EDIT}; do
	alias -s $filetype="$EDITOR";
done;
