#!/bin/zsh
alias datereadable='date +"%A %B %d, %Y"'

function saydate() {
	local todaysdate="$(date +'%A %B %d, %Y')"
	local currenthour="$(date +'%H')"
	local currentminute="$(date +'%M')"
	[[ $currentminute -lt 10 ]] && currentminute="O $currentminute";

	say "it's currently $currenthour $currentminute on $todaysdate";
}

function clock() {
	watch -c -t -n1 "date +'%H : %M : %S' | figlet" | lolcat;
}
