#!/bin/zsh

# --- Shortcuts for quick ARANDR switch -----------------------
alias undock="$DOTWRYN/config/xserver/screenlayout/undock.sh";
alias workdock="$DOTWRYN/config/xserver/screenlayout/workdock.sh";
alias homedock="$DOTWRYN/config/xserver/screenlayout/homedock_hdmionly.sh";
alias hdmidock="$DOTWRYN/config/xserver/screenlayout/hdmidock.sh";

# --- Note-taking facilitated ---------------------------------
NOTE_PATH='/Users/w0ryn/Documents/notes';
NOTE_EXTENSION='.txt';
alias mynotes='cd $NOTE_PATH';
function note() { vim $NOTE_PATH/$1$NOTE_EXTENSION; }
function notes() { NOTE="$NOTE_PATH/$1$NOTE_EXTENSION"; [ $1 ] && [ -f $NOTE ] && vim $NOTE || vim $NOTE_PATH; }

# --- GIT -----------------------------------------------------
alias gitbranchcleanup='git branch -d $(git branch | sed -E "/develop|master|\*/d")'


alias pd='pushd';
alias qd='popd';
alias ds='dirs';
alias cdo='cd $(xclip -o)';
