#!/bin/zsh
use desktop/xorg/i3 --group dotwryn

#####################################################################

dotwryn.desktop.xorg.i3.generate-config.parse.usage

MAIN() {
	dotwryn.desktop.xorg.i3.generate-config
}

#####################################################################
