#!/bin/zsh

use notify
use desktop/colorscheme --group dotwryn

DEPENDENCIES+=(i3lock)
#####################################################################

MAIN() {
	local SCWRYPTS_NOTIFICATION_ENGINES=(echo notify.desktop)
	local ARGS=(
		--ignore-empty-password
		--force-clock
		--pass-screen-keys
		--pass-media-keys
		--pass-volume-keys
		--pass-power-keys
		--verif-text=''
		--wrong-text=''
		--blur=11
		--insidever-color=$(dotwryn.desktop.colorscheme.get-hex 6)
		--ringver-color=$(dotwryn.desktop.colorscheme.get-hex 10)
		--insidewrong-color=$(dotwryn.desktop.colorscheme.get-hex 1)
		--ringwrong-color=$(dotwryn.desktop.colorscheme.get-hex 9)
		--inside-color=$(dotwryn.desktop.colorscheme.get-hex 0)
		--ring-color=$(dotwryn.desktop.colorscheme.get-hex 2)
		--time-color=$(dotwryn.desktop.colorscheme.get-hex 7)
		--date-color=$(dotwryn.desktop.colorscheme.get-hex 15)
		--keyhl-color=$(dotwryn.desktop.colorscheme.get-hex 11)
		--bshl-color=$(dotwryn.desktop.colorscheme.get-hex 13)
		)

	local RADIUS=$(xrandr | grep 'connected primary' | sed 's/.* \([0-9]\+\)x.*/\1/' | awk '{print int($1*0.08)}')
	[ $RADIUS ] && ARGS+=(--radius=$RADIUS)

	i3lock ${ARGS[@]} \
		|| notify.error 'something went wrong; unable to lock' \
	;
}
