#!/bin/zsh
cd "${0:a:h}"
while [[ $# -gt 0 ]]
do
	case $1 in
		--no-compile-vim ) NO_COMPILE_VIM=1 ;;
		--ci             ) export CI=1      ;;
		--force-root     ) FORCE_ROOT=1     ;;
		--no-fluff )
			NO_COMPILE_VIM=1
			;;
	esac
	shift 1
done
source ./requirements.zsh || exit 1
################################################################################

LOGFILE="$HOME/dotwryn-install.log"

__INFO "installation start : $(date)" 2>> "$LOGFILE"
{
	SETUP__OS     || __FAIL 1 'failed to set up os-dependencies (see above)'
	SETUP__CONFIG || __FAIL 2 'failed to set up program configuration (see above)'
} 2>&1 | tee --append "$LOGFILE"

__INFO "installation complete: $(date)" 2>> "$LOGFILE"

################################################################################
source "$DOTWRYN_PATH/setup/cleanup.zsh"
