#!/bin/bash

# --- Note-taking facilitated ---------------------------------
NOTE_PATH='/Users/w0ryn/Documents/notes';
NOTE_EXTENSION='.txt';
alias mynotes='cd $NOTE_PATH';
function note() { vim $NOTE_PATH/$1$NOTE_EXTENSION; }
function notes() { NOTE="$NOTE_PATH/$1$NOTE_EXTENSION"; [ $1 ] && [ -f $NOTE ] && vim $NOTE || vim $NOTE_PATH; }
