#!/bin/sh
# do not edit; generated by scwrypts
# theme : winter
#
# source this file to apply colorscheme to linux getty
#
[[ "$TERM" =~ ^linux$ ]] || return 0
/bin/echo -e " ]P0000505 ]P1d11455 ]P2906556 ]P300ffe7 ]P43d8890 ]P57b70af ]P650a3b5 ]P7d0f0f0 ]P8f48bae ]P9cfb8af ]PA8bfff4 ]PB1abcdd ]PC7d72fe ]PD86abb3 ]PEd0f0f0 ]PF7e707e "
[ ! $NO_CLEAR ] && clear
return 0
 sed $d
