#!/bin/sh
# do not edit; generated by scwrypts
# theme : spring-sunset
#
# source this file to apply colorscheme to linux getty
#
[[ "$TERM" =~ ^linux$ ]] || return 0
/bin/echo -e " ]P00b1e32 ]P1f12875 ]P25c68c4 ]P3f2e044 ]P45ab5e0 ]P5f5e878 ]P67983ce ]P7e8eaf7 ]P8f694bc ]P99fa6dc ]PAf8ef9e ]PBb9e5f4 ]PCfbf5c4 ]PDc5c9ea ]PEd0f0f0 ]PF7e707e "
[ ! $NO_CLEAR ] && clear
return 0
 sed $d
